-- AlterTable
ALTER TABLE `PublicPolicy` ADD COLUMN `healthRegion` VARCHAR(191) NULL,
    MODIFY `level` ENUM('NATIONAL', 'HEALTH_REGION', 'PROVINCIAL', 'DISTRICT', 'SUB_DISTRICT', 'VILLAGE') NOT NULL;
